// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	model "jrog_assignment/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// Downloader is an autogenerated mock type for the Downloader type
type Downloader struct {
	mock.Mock
}

// Download provides a mock function with given fields: in
func (_m *Downloader) Download(in model.DownloadJob) model.DownloadResult {
	ret := _m.Called(in)

	if len(ret) == 0 {
		panic("no return value specified for Download")
	}

	var r0 model.DownloadResult
	if rf, ok := ret.Get(0).(func(model.DownloadJob) model.DownloadResult); ok {
		r0 = rf(in)
	} else {
		r0 = ret.Get(0).(model.DownloadResult)
	}

	return r0
}

// NewDownloader creates a new instance of Downloader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDownloader(t interface {
	mock.TestingT
	Cleanup(func())
}) *Downloader {
	mock := &Downloader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
