// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	model "jrog_assignment/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// Reader is an autogenerated mock type for the Reader type
type Reader struct {
	mock.Mock
}

// Read provides a mock function with given fields: filePath, out
func (_m *Reader) Read(filePath string, out chan<- model.DownloadJob) error {
	ret := _m.Called(filePath, out)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, chan<- model.DownloadJob) error); ok {
		r0 = rf(filePath, out)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewReader creates a new instance of Reader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *Reader {
	mock := &Reader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
